services:
  backend:
    build: .
    container_name: upiq-backend
    image: upiq-backend:latest
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - upiq-net

  postgres:
    image: postgres:16
    container_name: upiq-postgres
    ports:
      - "5434:5432" # Exposed on port 5433 locally to avoid conflicts with 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - upiq-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  upiq-net:
    driver: bridge

volumes:
  postgres_data:
